### ISSUE TITLE
AbstractString InvalidArgumentException not thrown if string is empty after normalizing.

### ISSUE THREAD

**Issue by KevinVanSonsbeek** [aeviiq/value-object#10]
When you create an AbstractString value object, if the string becomes empty during the normalization, no `InvalidArgumentException` is thrown. 

Testcase:
```php
<?php

declare(strict_types=1);

use Aeviiq\ValueObject\AbstractString;
use PHPUnit\Framework\TestCase;

final class StringValueTestCase extends TestCase
{
    public function testConstruct(): void
    {
        $this->expectException(InvalidArgumentException::class);

        new class('test') extends AbstractString
        {
            public static function getConstraints(): array
            {
                return [];
            }

            protected function normalize($value): string
            {
                return '';
            }
        };
    }
}

```

**Comment by aeviiq** [comment]
In which situation would you normalize the string and it ends up empty? Validation is done after normalization, so you could always add a NotBlank constraint or any other constraint that should be applied to the string. If any of the constraints is violated it will throw the InvalidArgumentException as well.

**Comment by nusje2000** [comment]
I've talked with @aeviiq and we will remove the exception all together, if a value should not be empty by the domain definition, that should be defined by the user by adding a NotBlank constraint. This will also fix this issue where the normalizer results in an empty string, since then the NotBlank will fail.

**Comment by nvdbeek** [comment]
@aeviiq can you close this issue?
