### ISSUE TITLE
isEqualsTo in AbstractValue compares value of same object

### ISSUE THREAD

**Issue by dbrekelmans** [aeviiq/value-object#3]
In `Aeviiq\ValueObject\AbstractValue` on line 30:

```php
final public function isEqualTo($value): bool
{
    if ($value instanceof self) {
        return $value === $value->get();
    }

    return $value === $this->value;
}
```

`return $value === $value->get();` should be `return $this->value === $value->get();`

**Comment by aeviiq** [comment]
Fixed in https://github.com/aeviiq/value-object/commit/9420957352c1e1e5b9b22e1466bd4f2a40725a7b
